---
title: "ggplot2 - Oefening"
authors: [ivyjansen, pieterverschelde]
output: pdf_document
papersize: a4
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Maak je vertrouwd met de `airquality` data in `R`

1. Bekijk de help file van `airquality`.
1. Welke variabelen zitten in de dataset?
    a. Van welk datatype zijn deze variabelen?
1. Vraag een `summary()` van de gegevens.
    a. Voor welke maanden beschikken we over gegevens?
    a. In welke eenheid is de temperatuur gemeten?
    a. Zijn er ontbrekende waarden voor bepaalde variabelen?



# Verkennende plotjes

Wees aandachtig voor warnings en foutmeldingen. Probeer deze te begrijpen alvorens verder te gaan met de oefening.

1. Bekijk de verdeling van de temperatuur.
    a. Maak hiervoor een histogram. 
    a. Verander `binwidth = 5`.
1. Bekijk de verdeling over de maanden.
    a. Maak hiervoor een barplot.
1. Verschilt de gemeten temperatuur per maand?
    a. Maak hiervoor een boxplot.
    a. Splits deze op volgens maand.
    a. Krijg je de figuur die je in gedachten had? Waarom (niet)? Lees zeker de warning.
    a. Hoe kan je dit oplossen?
1. Is er een verband tussen temperatuur en ozon? 
    a. Maak hiervoor een scatterplot.
    a. Voeg een (al dan niet lineaire) smoother toe.
    a. Wat betekent de warning? Moeten we hiervoor iets aanpassen?
    a. Verander de titel in "Verband tussen temperatuur en ozon".
    a. Kies duidelijke namen (met eenheid) voor de X- en Y-assen.
1. Is het verband tussen temperatuur en ozon afhankelijk van de straling van de zon?
    a. Voeg aan de vorige scatterplot een kleur toe voor zonnestraling.
    a. Kunnen we nu ook afzonderlijke smoothers voor de zonnestraling bepalen? Waarom (niet)?
1. Is het verband tussen temperatuur en ozon afhankelijk van de maand?
    a. Maak hiervoor per maand een scatterplot met een rode lineaire smoother.
    a. Bewaar deze figuur in de map "Figuren/" onder de naam "TempOzon_PerMaand.png".

