---
title: "R en RStudio - Huistaak"
authors: [ivyjansen, pieterverschelde, thierryo]
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



__Hoe download je een script__? Klik op de link `Code`. Het script wordt geopend. Zoek nu de knop `Raw`. Rechtsklik op deze knop en kies `Link opslaan als...` Navigeer naar de `src` folder en bewaar het bestand.

__Hoe download je een dataset__? Klik op de link `Data` en zoek de dataset. Klik op deze dataset. Afhankelijk van de extensie krijg je de dataset reeds te zien, of een *blanco* pagina. Zoek in het eerste geval de knop `Raw`, in het tweede geval de knop `Download`. Rechtsklik op deze knop en kies `Link opslaan als...` Navigeer naar de `data` folder en bewaar het bestand.



# Herhaling lesmateriaal

- Download het materiaal van de [eerste les](https://inbo.github.io/tutorials/tutorials/r_beginners/)
- Doorloop het document rond **R en RStudio**, eventueel met behulp van het script
    - Noteer alle onduidelijkheden en mail die naar Ivy (ivy.jansen@inbo.be)
    - Probeer ook eens de andere (online) manieren om hulp te zoeken dan degene die in de les aangehaald werden



# Voorbereidend werk voor volgende les

1. Installeer de packages `tidyverse` en `googlesheets`
1. Maak een nieuw project aan in een folder waar je interessante datasets hebt staan die je graag in R wil importeren en visualiseren 



# Vectoren

1. Maak een vector met tien diameters
1. Bereken een vector met de overeenkomstige omtrekken (omtrek = $\pi$ * diameter)
1. Tel bij elke diameter 10 cm op
1. Bereken het gemiddelde van de eerste vier omtrekken
1. Bereken de standaard afwijking van alle omtrekken behalve de vijfde
    - TIP: *standard deviation* 



# Dataframe

1. Maak een dataframe met een kolom 'Diameter' die tien waarden bevat
1. Bereken de omtrek en voeg die toe aan de dataframe
1. Bereken de oppervlakte en voeg die toe aan de dataframe (oppervlakte = $\pi$ * straal$^2$)
