---
title: "Further reading"
date: 2018-03-21
link-citations: yes
csl: ../inbo.csl
bibliography: reproducible_research.bib
---

This page lists **selected** literature and online resources. Some are related to existing tutorial pages, while others are not. They are supposed to be of high interest to this site's users.

Several of the resources were added based on an inspiring
[talk](https://docs.google.com/presentation/d/10KkXEv4r3wWtdKvB6RFOPe809eMNldODaRqQxn-jeME/edit?usp=sharing) 
by Julia Lowndes at the SAFRED conference, Brussels, 27 Feb 2018.



## Scientific computing and data handling workflows

### Overviews {#overviews}

- @wilson_good_2017: set of **good computing practices** that every researcher can adopt
- @british_ecological_society_guide_2014: planning the **data life cycle**; creating, processing, documenting, preserving, sharing & reusing data
- @cooper_guide_2017: file organisation, workflow documentation, **code** reproducibility and readability, writing reproducible reports, version control and code archiving
- @ibanez_practicing_2014: vision on reproducible science, routine **practices**, collaboration, literate computing

See also some resources related to [learning and education](#educate) and the [discipline of open and reproducible science](#discipline).

### Specific tools

- @ross_declutter_2017: about **tidyverse** workflow and tools


### Focus on version control workflows

- @bryan_excuse_2017: rationale, workflows and tools regarding version control for project organization



## Sharing and communicating


### Sharing data

- @ellis_how_2017: guidelines for **providing data** to a scientist / statistician: provide raw data, format consistently, include metadata & preprocessing steps
- @wilkinson_fair_2016: the **FAIR data principles**: date are to be findable, accessible, interoperable and reusable
- @culina_navigating_2018: overview of online **data infrastructures** and considerations to be made
- @perkel_democratic_2016: **data repository sites** like github and others


### Communicating

- @smith_software_2016: recommendations of the FORCE11 Software Citation Working Group



## Acquiring the skills (learning and teaching) {#educate}

These resources focus on the learning and teaching aspect, while they often also give an overview of scientific computing workflows (as [above](#overviews)).

### Open data science in general

- @lowndes_our_2017: **learning** open data science tools
- @hampton_skills_2017: **training approaches and needed skills** in data science
- @stevens_building_2018: **local community of practice** for scientific programming: why, how (including scheme), challenges

### In relation to statistics teaching

- @kaplan_teaching_2017: ten organizing blocks for **introductory statistics teaching** in the present data science context
- @cetinkaya-rundel_infrastructure_2017: **computational infrastructure and toolkit choices** to allow for the necessary pedagogical innovations in statistics education


## The discipline of open science {#discipline}

These resources focus on the discipline as a whole, its perception, principles ,etc., while they often also give an overview of scientific computing workflows (as [above](#overviews)).

- @ibanez_practicing_2014: open and reproducible science: vision, routine practices, collaboration, literate computing
- @hampton_tao_2015: workflows, tools, obstacles and needed mindshifts for open science
- @donati_information_2017: how data science is becoming a large discipline


### Focus on reproducible research

- @stodden_implementing_2014: **book** on computational reproducibility and (experiment) replicability; the three parts are *Tools*, *Practices and Guidelines*, *Platforms*
- @stodden_best_2014: a formalized set of **best practice recommendations** for reproducible research
- @begley_institutions_2015: current **irreproducibility** and good institutional practice




## Bibliography


