---
title: "Les 1 - Huistaak"
author: "Ivy Jansen, Pieter Verschelde, Thierry Onkelinx"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Herhaling lesmateriaal

- Download het materiaal in de [map van de eerste les](https://drive.google.com/open?id=1JqrhxD1ET3ZzaCIQm0_DknNRxpvJYnJu)
- Doorloop het [document rond R en RStudio](https://drive.google.com/open?id=1FpDxeehjDQTbjCPKvtJOzLlxDbmEn0Sq), eventueel met behulp van het [script](https://drive.google.com/open?id=1kxziG2A_gm_3f8yMRN5fTbEsMjKrHz2G)
    - Noteer alle onduidelijkheden en mail die naar Ivy (ivy.jansen@inbo.be)
    - Probeer ook eens de andere (online) manieren om hulp te zoeken dan degene die in de les aangehaald werden
    - Maak een nieuw project aan in een folder waar je interessante datasets hebt staan die je graag in R wil importeren en visualiseren 
    - Installeer de packages `tidyverse` en `googlesheets`
- Lees de eerste 2 pagina's van het [document rond inlezen van gegevens](https://drive.google.com/open?id=1AAff1K8mSFSW8UXtKfMqSorKdrmGzB1D)
    - Noteer alle onduidelijkheden en mail die naar Pieter (pieter.verschelde@inbo.be)
    - Doorloop het [basisscript met voorbeelden](https://drive.google.com/open?id=1Gb7S8qEdDPxhBvFqDfBiRZGe7hw0WE9m) om gegevens uit allerlei files in te lezen. Hiervoor heb je de extra datasets nodig die toegevoegd zijn in de [map data](https://drive.google.com/open?id=19xblHJvpJ7VJ94HNi2g6cH9JBaSaAVvX)



# Vectoren

1. Maak een vector met tien diameters
1. Bereken een vector met de overeenkomstige omtrekken (omtrek = $\pi$ * diameter)
1. Tel bij elke diameter 10 cm op
1. Bereken het gemiddelde van de eerste vier omtrekken
1. Bereken de standaard afwijking van alle omtrekken behalve de vijfde
    - TIP: *standard deviation* 



# Dataframe

1. Maak een dataframe met een kolom 'Diameter' die tien waarden bevat
1. Bereken de omtrek en voeg die toe aan de dataframe
1. Bereken de oppervlakte en voeg die toe aan de dataframe (oppervlakte = $\pi$ * straal$^2$)



# Lees een dataset in

- Probeer enkele van je eigen datasets in te lezen. Doe dit vanuit het nieuwe project dat je in het begin van deze huistaak aangemaakt hebt. Kies minstens 2 formaten uit
    - csv
    - txt
    - Excel
    - Access
    - Googlesheet
