---
title: "Sharing and communicating"
date: 2018-03-21
csl: '`r cslfile <- file.path(tempdir(), "research-institute-for-nature-and-forest.csl"); download.file("https://github.com/inbo/styles/raw/inbocsl-0.1.0/research-institute-for-nature-and-forest.csl", cslfile); cslfile`'
bibliography: ../reproducible_research.bib
categories: ["literature"]
tags: ["literature", "open science"]
output: 
    md_document:
        preserve_yaml: true
weight: 4
---

This page lists **selected** literature and online resources. Some are related to existing tutorial pages, while others are not. They are supposed to be of high interest to this site's users.

Several of the resources were added based on an inspiring
[talk](https://docs.google.com/presentation/d/10KkXEv4r3wWtdKvB6RFOPe809eMNldODaRqQxn-jeME/edit?usp=sharing) 
by Julia Lowndes at the SAFRED conference, Brussels, 27 Feb 2018.

## Sharing data

- @ellis_how_2017: guidelines for **providing data** to a scientist / statistician: provide raw data, format consistently, include metadata & preprocessing steps
- @wilkinson_fair_2016: the **FAIR data principles**: date are to be findable, accessible, interoperable and reusable
- @culina_navigating_2018: overview of online **data infrastructures** and considerations to be made
- @perkel_democratic_2016: **data repository sites** like github and others

## Communicating

- @smith_software_2016: recommendations of the FORCE11 Software Citation Working Group

## Bibliography
