---
title: "The discipline of open science"
date: 2020-09-23
csl: '`r cslfile <- file.path(tempdir(), "research-institute-for-nature-and-forest.csl"); download.file("https://github.com/inbo/styles/raw/inbocsl-0.1.0/research-institute-for-nature-and-forest.csl", cslfile); cslfile`'
bibliography: ../reproducible_research.bib
categories: ["literature"]
tags: ["literature", "open science"]
output: 
  md_document:
    preserve_yaml: true
    variant: gfm
---

This page lists **selected** literature and online resources. Some are related to existing tutorial pages, while others are not. They are supposed to be of high interest to this site's users.

Several of the resources were added based on an inspiring
[talk](https://docs.google.com/presentation/d/10KkXEv4r3wWtdKvB6RFOPe809eMNldODaRqQxn-jeME/edit?usp=sharing) 
by Julia Lowndes at the SAFRED conference, Brussels, 27 Feb 2018.

These resources focus on the discipline as a whole, its perception, principles, etc., while they often also give an overview of [scientific computing workflows](../computing).

- @ibanez_practicing_2014: open and reproducible science: vision, routine practices, collaboration, literate computing
- @hampton_tao_2015: workflows, tools, obstacles and needed mindshifts for open science
- @donati_information_2017: how data science is becoming a large discipline


## Focus on reproducible research

- @stodden_implementing_2014: **book** on computational reproducibility and (experiment) replicability; the three parts are *Tools*, *Practices and Guidelines*, *Platforms*
- @stodden_best_2014: a formalized set of **best practice recommendations** for reproducible research
- @begley_institutions_2015: current **irreproducibility** and good institutional practice
- @ropensci_contributors_reproducibility_2018: a comprehensive **overview** of aspects and R-oriented tools in reproducible research

## Bibliography
