---
title: Styleguide for repositories
author: Peter Desmet
tags: GitHub, repositories
---

## I want a new repository

### Creating a repository

* Repository name
* Description
* Public vs private
* Initialize with README
* .gitignore
* License

### Minimal README

* Title
* Rationale
* How you can contribute

### Topics

Select from the appropriate topics from the following keywords: ...

### Repo settings

* Wikis
* Collaborators & teams
* Branches

## I want to contribute to a repository

### Contributing guidelines

* Directory structure
* Naming conventions (e.g. lowercase for repository, directory, and file names. For R-related files, use uppercase `R`.)
* Coding conventions
* Documentation conventions

### I noticed a typo

* Working directly on github.com

### I want to work on this repo locally

* Forking
* Cloning
* Feature branches
* Commits
* Push
* Pull requests

## Managing teams (maybe this should be another styleguide)

* Creating a team
* Inviting people
* Inviting as outside collaborators
