---
title: "Git handson session"
author: "Stijn Van Hoey, Peter Desmet"
date: "March 29, 2017"
output:
  revealjs::revealjs_presentation:
    theme: simple
    highlight: zenburn
    transition: none
    center: true
    fig_width: 7
    fig_height: 6    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Personal workflow

---
## Backup your work
* Create your own repository online
* Connect your local Git with Github

```
git config -- global user.name 'Your Name Here'
git config -- global user.email 'email@example.com'
```
* `git clone` to your computer

---
* Adapt your `README.md` on Github
* Adapt your `README.md` local
* `git push/pull` your local changes
* CONFLICT!?!

---
## The story of your project
* Add a new file to your repository
* `git diff` and `git status` the changes
* `git commit` the addition of the new file
* Adapt your `README.md` again in two different sections
* `git diff` and `git status` the changes
* `git commit` these changes in two separate commits

---
* Apparently, a small typo in the last commit
* `git amend` the typo to your last commit

---
* Backup - `git push` - your local work to Github

## Travel back in time
* Explore your `git log`
* Explore the `log` on Github and write down the HASH of your fist commit

* **Linux user Tip:** Add an alias to your `.bash_aliases`:
```
alias glog="git log --graph --pretty=format:'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset' --abbrev-commit --date=relative"
```

---
Exploration from history (READ-ONLY)
* `git checkout` to your first commit
* Check the local folder and files on your computer
* `git checkout master` to your latest work again

---
Undo when not yet commit 
* Change a value in your data file
* Save the file
* Undo this change `git checkout -- datafilename`

---
Undo when already commit
* Change a value in any of your files
* Save the file
* `git commit` your adaptation
* `git revert HEAD` (go back one commit)
* Check the file again

**Remark:** `git revert` can be applied to any commit, more in depth information about undoing of commits is given in LINK TO MD TODO

---
## Experiment with changes



* Restart experimenting from a previous commit: `git checkout -b old-state 0d1d7fc32`
---

# Working together

## Teaming up


## Online collaboration


## Working local - merging online
    

## Release





