---
title: 'Les1: Huistaak'
author: "Ivy, Pieter en Thierry"
date: "18 februari 2020"
output:
  pdf_document: default
  html_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Taak 1
* Doorloop de handleiding van de eerste les
    * Noteer alle onduidelijkheden en mail die naar Pieter en Raisa(pieter.verschelde@inbo.be, raisa.carmen@inbo.be)
    * Probeer ook eens de andere (online) manieren om hulp te zoeken dan degene die in de les aangehaald werden

## Taak 2: Maak een project aan en installeer de nodige packages

1. Installeer de packages tidyverse, remotes, googlesheets4 en googledrive
1. Maak een nieuw project aan in een folder waar je interessante datasets hebt staan die je graag in R
wil importeren en visualiseren

## Taak 3: Oefening R code

### Vectoren

1. Maak een vector met tien diameters
    * gebruik eventueel de functie `runif` (gebruik R help) hiervoor
2. Bereken een vector met de overeenkomstige omtrekken (omtrek = pi * diameter)
3. Tel bij elke diameter 10 cm op
4. Bereken het gemiddelde van de eerste vier omtrekken
5. Bereken de standaard afwijking van alle omtrekken behalve de vijfde
    * TIP: Zoek uit welke functie in R de standaarddeviatie (standard deviation) berekent

### Dataframe

1. Maak een dataframe met een kolom ‘Diameter’ die tien waarden bevat
2. Bereken de omtrek en voeg die toe aan de dataframe
3. Bereken de oppervlakte en voeg die toe aan de dataframe (oppervlakte = pi * straal^2)

## Taak 4: Wegschrijven en inlezen (indien dit reeds in de les behandeld is)

1. Bewaar je data.frame in een csv bestand in de folder ./data in je project die je in taak 2 aanmaakte
1. Lees de data.frame terug in vanuit dit bestand.
