---
title: "Huistaak Rmarkdown"
authors: [ivyjansen, pieterverschelde, raisacarmen]
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Herhaling lesmateriaal

- Herhaal het lesmateriaal
- Als er iets onduidelijk is, en online bronnen kunnen je niet helpen, contacteer Pieter (pieter.verschelde@inbo.be) of Raïsa (raisa.carmen@inbo.be)


## Opdracht

- Neem het uitgewerkte script van de oefening (of huistaak) van les 2 of les 3
    - `airquality` dataset
    - **Pilootstudie**
    - Demografie provincie hoofdsteden
    - Neerslaggegevens
- Maak een Rmarkdown document van het script
    - Zet alle code in kleine chunks
        - Geef elke chunk een duidelijke naam
        - Denk goed na over de opties (wat wil je tonen in het rapport?)
    - Voeg formattering toe
        - Titels die verwijzen naar de verschillende onderdelen in de opgave
        - Lijsten om de nummering te volgen
        - **Bold** of *italic* waar gepast
    - Wissel af met platte tekst. Dit kan een selectie zijn uit
        - Eigen commentaar
        - Interpretatie van de grafieken
        - Ondervonden moeilijkheden
        - Alternatieve oplossingen
    - Voorzie het document van een titel, en jouw naam
- `Knit` dit document naar een html-file
- Mail de .Rmd file en de html-output naar Ivy, **ten laatste 30 juni 23u59**

